### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VitaliyYerin** [VitaliyYerin/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by yerinSergey** [comment]
**Donald Tramp**

- https://www.fb.com/DonaldTrump
- donaldTrump@gmail.com
- https://twitter.com/realDonaldTrump
- https://www.instagram.com/realDonaldTrump/
